### ISSUE TITLE
The UI needs a "reconnect" button

### ISSUE THREAD

**Issue by PaoloMasci** [thehogfather/pvsio-web#188]
The reconnect button on the UI allows to re-connect a client to the server without re-loading the webpage in the browser. This is useful in the case the server crashes and we have unsaved changes -- rather than reloading the webpage in the browser, one should be able to just click the reconnect button to connect to the server (when the server become again available).

**Comment by thehogfather** [comment]
This is a good idea. We can also show a small pop up to notify the user that the server seems to have crashed, ask the user to restart the server and then click the reconnect button to continue working. It might be a good idea for the dialog to be modal so that nothing can be done on the client until the server is restarted and the client reconnected to the server.

**Comment by PaoloMasci** [comment]
We should think about an "offline mode" -- in this mode, users can do everything except running the prototype or typechecking
