### ISSUE TITLE
[issue] Saving with firefox

### ISSUE THREAD

**Issue by saulors** [thehogfather/pvsio-web#208]
When using FF to OSX, sometimes the projects are not saved.

**Comment by PaoloMasci** [comment]
The issue seems to be linked to the implementation of the Save Project handler in Prototype Builder, which calls save emuchart and save project in sequence, but the second call (save project) does not wait the completion of the first call (save emuchart). In some cases, this causes the emuchart diagram to be overwritten with an old version of the diagram.
