### ISSUE TITLE
[Issue] In Emucharts editor

### ISSUE THREAD

**Issue by saulors** [thehogfather/pvsio-web#209]
There`s no way to scrool the page up or down, unless the cursor is over emucharts editor toolbox (chrome, osx)

**Comment by PaoloMasci** [comment]
The issue is due to the behaviour of d3 zoom handler, which does not bubble scroll events to the web page even if we don't use preventDefault. The solution is to remove d3 handler when we are not dragging the svg canvas (mouse down + zoom events), and re-install the d3 handler wheneve the mouse is moved.

**Comment by PaoloMasci** [comment]
on OSx the implemented solution is still not working -- need to investigate the causes.
